<header class="header-section header-normal">

    <!-- Register & Login -->
    <div class="top-nav">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="tn-right">
                        <a href="/signup" class="bk-btn">Register</a>
                        <a href="/login" class="bk-btn">Log In</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="menu-item">
        <div class="container">
            <div class="row">
                <div class="col-lg-7">      
                    <div class="nav-menu">
                        <nav class="mainmenu">
                            <div class="logo">
                                <a href="/">
                                    <img src="img/icons/MainIcon.png" alt="">
                                </a>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Navbar -->
    <div class="menu-item">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">      
                    <div class="nav-menu">
                        <nav class="mainmenu">
                            <ul>
                                <li><a href="">Home</a></li>
                                <li><a href="">Rooms</a></li>
                                <li><a href="">About Us</a></li>
                                <li><a href="">Booking</a>
                                <li><a href="">Contact</a>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>